"""Regression tests for the Phase 2 role-based Data Understanding merge:

1. detect_dataset_type() no longer misclassifies a customer-level table as "general" just
   because one of its columns happens to be a timestamp (e.g. signup_date) — rows-per-
   customer is checked first, since a signup date is a per-customer ATTRIBUTE, not
   evidence this is really a per-event/per-period log.
2. detect_post_outcome_columns() replaces the old correlation-vs-an-arbitrary-target
   heuristic (proven unreliable: a genuine leak and pure statistical noise can both show
   under 1% correlation) with a target-independent structural signal: the same
   post-outcome-hint word means "this row's own reaction" in a transaction_log/time_series
   dataset (one row per event) but "an accumulated historical attribute" in a
   customer_level dataset (one row per customer) — and must only fire in the former.
"""

import os

import pandas as pd

from app.services import data_understanding_service as dus
from app.services import dataset_service

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")


def _dataset_type_for(fname: str) -> tuple[str, dict]:
    df = pd.read_csv(os.path.join(DATA_DIR, fname))
    profile = dataset_service.build_dataset_profile(df)
    column_roles = dus.classify_columns(df, profile, use_gemini=False)
    dataset_type = dus.detect_dataset_type(df, column_roles)
    return dataset_type["type"], column_roles


def test_churn_dataset_is_customer_level_despite_having_a_signup_date_column():
    """Regression test for the reordering fix: customer_churn_dataset.csv has both a
    customer_id (one row each) and a signup_date timestamp column — before the fix, the
    timestamp presence alone incorrectly disqualified the customer_level branch, and the
    dataset fell through to the catch-all 'general' type."""
    dtype, _ = _dataset_type_for("customer_churn_dataset.csv")
    assert dtype == "customer_level"


def test_retention_dataset_is_customer_level_despite_having_a_signup_date_column():
    dtype, _ = _dataset_type_for("customer_retention_training.csv")
    assert dtype == "customer_level"


def test_telecom_dataset_is_customer_level_despite_having_an_activation_date_column():
    dtype, _ = _dataset_type_for("telecom_subscribers_usage.csv")
    assert dtype == "customer_level"


def test_retail_and_karachi_stay_time_series_unaffected_by_the_reordering():
    """Neither has a customer_id column at all, so they were never affected by the
    timestamp-disqualifies-customer_level bug — confirms the reordering fix didn't change
    their classification."""
    assert _dataset_type_for("retail_sales_dataset.csv")[0] == "time_series"
    assert _dataset_type_for("karachi_food_delivery_dataset.csv")[0] == "time_series"


def test_complaints_last_6_months_not_flagged_as_post_outcome_in_real_telecom_data():
    """The case that motivated this redesign: complaints_last_6_months matches the
    'complaint' post-outcome hint by name, but telecom is customer-level (one row per
    subscriber, verified above) — the structural gate must keep it un-flagged regardless
    of any correlation with a hypothetical target, since correlation-based evidence was
    proven unable to reliably tell this apart from a genuine leak (both can show under 1%
    correlation)."""
    dtype, roles = _dataset_type_for("telecom_subscribers_usage.csv")
    flagged = {w["column"] for w in dus.detect_post_outcome_columns(roles, dtype)}
    assert "complaints_last_6_months" not in flagged


def test_customer_rating_and_returned_flagged_as_post_outcome_in_real_retail_data():
    """retail_sales_dataset.csv is time_series (one row per sale) — customer_rating and
    returned both describe a reaction to that specific sale and must be flagged, even
    though their real correlation with sales_amount is under 4% (proven too weak for the
    old correlation-based mechanism to reliably catch)."""
    dtype, roles = _dataset_type_for("retail_sales_dataset.csv")
    flagged = {w["column"] for w in dus.detect_post_outcome_columns(roles, dtype)}
    assert "customer_rating" in flagged
    assert "returned" in flagged


def test_product_returns_not_flagged_as_post_outcome_in_real_retention_data():
    """customer_retention_training.csv is customer_level — product_returns is a
    customer's cumulative PAST return count, not a reaction generated by whatever gets
    predicted, so it must not be flagged despite matching the 'return' hint."""
    dtype, roles = _dataset_type_for("customer_retention_training.csv")
    flagged = {w["column"] for w in dus.detect_post_outcome_columns(roles, dtype)}
    assert "product_returns" not in flagged
