"""initial schema

Revision ID: 18900b41c80e
Revises: 
Create Date: 2026-09-23 11:57:18.766887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.types


revision: str = '18900b41c80e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('user_id', app.core.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_column', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_conversations',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('project_id', app.core.types.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('project_id', app.core.types.GUID(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('missing_values', sa.Integer(), nullable=True),
    sa.Column('duplicate_rows', sa.Integer(), nullable=True),
    sa.Column('profile_json', sa.JSON(), nullable=True),
    sa.Column('is_cleaned', sa.Boolean(), nullable=False),
    sa.Column('cleaning_log_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_messages',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('conversation_id', app.core.types.GUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_runs',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('dataset_id', app.core.types.GUID(), nullable=False),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('results_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_columns',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('dataset_id', app.core.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dtype', sa.String(length=50), nullable=False),
    sa.Column('semantic_type', sa.String(length=50), nullable=True),
    sa.Column('missing_count', sa.Integer(), nullable=False),
    sa.Column('unique_count', sa.Integer(), nullable=False),
    sa.Column('is_numeric', sa.Boolean(), nullable=False),
    sa.Column('is_categorical', sa.Boolean(), nullable=False),
    sa.Column('is_datetime', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('project_id', app.core.types.GUID(), nullable=False),
    sa.Column('dataset_id', app.core.types.GUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=False),
    sa.Column('problem_type', sa.String(length=50), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=False),
    sa.Column('feature_columns_json', sa.JSON(), nullable=True),
    sa.Column('preprocessing_json', sa.JSON(), nullable=True),
    sa.Column('hyperparameters_json', sa.JSON(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('feature_importance_json', sa.JSON(), nullable=True),
    sa.Column('comparison_json', sa.JSON(), nullable=True),
    sa.Column('is_best', sa.Boolean(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('model_path', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('model_id', app.core.types.GUID(), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('project_id', app.core.types.GUID(), nullable=False),
    sa.Column('dataset_id', app.core.types.GUID(), nullable=True),
    sa.Column('model_id', app.core.types.GUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('report_path', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('predictions')
    op.drop_table('models')
    op.drop_table('dataset_columns')
    op.drop_table('analysis_runs')
    op.drop_table('ai_messages')
    op.drop_table('datasets')
    op.drop_table('ai_conversations')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
