"""auto analyze force target reselection

Revision ID: 77970e2cf32b
Revises: 87e73f79aa87
Create Date: 2026-09-24 09:21:41.962624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.types


revision: str = '77970e2cf32b'
down_revision: Union[str, None] = '87e73f79aa87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'auto_analyze_jobs',
        sa.Column('force_target_reselection', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('auto_analyze_jobs', 'force_target_reselection', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_analyze_jobs', 'force_target_reselection')
    # ### end Alembic commands ###
