"""add ai insight cache table

Revision ID: 83d96e982408
Revises: 77970e2cf32b
Create Date: 2026-09-25 02:52:33.535559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.types


revision: str = '83d96e982408'
down_revision: Union[str, None] = '77970e2cf32b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insight_cache',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('project_id', app.core.types.GUID(), nullable=False),
    sa.Column('dataset_id', app.core.types.GUID(), nullable=True),
    sa.Column('model_id', app.core.types.GUID(), nullable=True),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('insight', sa.Text(), nullable=False),
    sa.Column('ai_available', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insight_cache_cache_key'), 'ai_insight_cache', ['cache_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_insight_cache_cache_key'), table_name='ai_insight_cache')
    op.drop_table('ai_insight_cache')
    # ### end Alembic commands ###
