"""auto analyze target confirmation

Revision ID: 87e73f79aa87
Revises: 9917f544f687
Create Date: 2026-09-24 04:28:26.928448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.types


revision: str = '87e73f79aa87'
down_revision: Union[str, None] = '9917f544f687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_analyze_jobs', sa.Column('target_candidates_json', sa.JSON(), nullable=True))
    op.add_column('auto_analyze_jobs', sa.Column('confirmed_target_column', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_analyze_jobs', 'confirmed_target_column')
    op.drop_column('auto_analyze_jobs', 'target_candidates_json')
    # ### end Alembic commands ###
