"""smart features: id detection, cleaning versioning, feature schema, auto analyze jobs

Revision ID: 9917f544f687
Revises: 18900b41c80e
Create Date: 2026-09-24 02:48:01.300897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.types


revision: str = '9917f544f687'
down_revision: Union[str, None] = '18900b41c80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_analyze_jobs',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('project_id', app.core.types.GUID(), nullable=False),
    sa.Column('dataset_id', app.core.types.GUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('steps_json', sa.JSON(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'dataset_columns',
        sa.Column('is_id_like', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('datasets', sa.Column('original_storage_path', sa.String(length=1000), nullable=True))
    op.add_column(
        'datasets',
        sa.Column('cleaning_version', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column('models', sa.Column('feature_schema_json', sa.JSON(), nullable=True))
    # Backfill original_storage_path for pre-existing datasets so cleaning stays reproducible.
    op.execute("UPDATE datasets SET original_storage_path = storage_path WHERE original_storage_path IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'feature_schema_json')
    op.drop_column('datasets', 'cleaning_version')
    op.drop_column('datasets', 'original_storage_path')
    op.drop_column('dataset_columns', 'is_id_like')
    op.drop_table('auto_analyze_jobs')
    # ### end Alembic commands ###
